Repository kaltura/playkit-js-ui, pull requests merged in 2018-11, with the labels that each got.

#285 feat(FEC-8623): playlist UI
  src/components/engine-connector/engine-connector.js
  src/components/overlay-action/_overlay-action.scss
  src/components/play-pause/_play-pause.scss
  src/components/playback-controls/_playback-controls.scss
  src/components/playback-controls/index.js
  src/components/playback-controls/playback-controls.js
  src/components/playlist-button/_playlist-button.scss
  src/components/playlist-button/playlist-button.js
  src/components/playlist-countdown/_playlist-countdown.scss
  src/components/playlist-countdown/index.js
  src/components/playlist-countdown/playlist-countdown.js
  src/components/seekbar/_seekbar.scss
  src/components/shell/shell.js
  src/reducers/engine.js
  src/styles/style.scss
  src/translations/en.json
  src/ui-presets/ads.js
  src/ui-presets/live.js
  src/ui-presets/playback.js
Labels: Priority: High

#291 fix(FEC-8644): the playlist jumps to the last item - safari and FF
  src/components/engine-connector/engine-connector.js
Labels: Priority: High, Type: Bug

#292 fix(FEC-8603): native captions are overlapped by toolbar
  src/styles/_captions.scss
Labels: Priority: High, Type: Bug

#294 fix(FEC-8669): countdown skips the postroll
  src/components/engine-connector/engine-connector.js
  src/components/playlist-countdown/playlist-countdown.js
  src/reducers/engine.js
Labels: Priority: High, Type: Bug

#295 fix(FEC-8671): sometimes the playlist skip to the next item immediately, with no countdown - safari
  src/components/engine-connector/engine-connector.js
  src/components/playlist-countdown/playlist-countdown.js
  src/reducers/engine.js
Labels: Priority: High, Type: Bug

#298 fix(FEC-8683): playlist by config, no ui for the second entry and onwards
  src/components/playlist-button/playlist-button.js
  src/components/playlist-countdown/playlist-countdown.js
Labels: Priority: High, Type: Bug

#302 fix(FEC-8686): the playlist jumps to the last item (in case setting timeToShow)
  src/components/engine-connector/engine-connector.js
Labels: Priority: High, Type: Bug

#303 fix: disabled playlist button is black
  src/components/icon/icon.js
  src/components/icon/icon.scss
  src/components/playlist-button/_playlist-button.scss
  src/components/playlist-button/playlist-button.js
Labels: Priority: High, Type: Bug

#307 chore: fix typo in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Priority: Low
