Repository kaltura/playkit-js-ui, pull requests merged in 2018-03, with the labels that each got.

#188 fix(FEC-7964): touch while playing on mobiles always pause/resume the video
  src/components/overlay-action/overlay-action.js
  src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
  src/components/shell/shell.js
Labels: Priority: High, Type: Bug

#191 fix(FEC-7971): change media doesn't work after a critical error
  src/components/engine-connector/engine-connector.js
  src/components/error-overlay/error-overlay.js
  src/reducers/engine.js
  src/ui-presets/error.js
Labels: Priority: High, Type: Bug

#192 feat: support external component config
  dist/playkit-ui.js
  dist/playkit-ui.js.map
  src/components/error-overlay/error-overlay.js
  src/components/fullscreen/fullscreen.js
  src/components/seekbar-playback-container/seekbar-playback-container.js
  src/components/seekbar/seekbar.js
  src/components/shell/shell.js
  src/reducers/config.js
  src/ui-manager.js
  src/ui-presets/ads.js
  src/ui-presets/error.js
  src/ui-presets/live.js
  src/ui-presets/playback.js
  src/utils/component-config.js
Labels: Type: Feature

#190 feat: watermark support
  dist/playkit-ui.js
  dist/playkit-ui.js.map
  docs/configuration.md
  src/components/watermark/_watermark.scss
  src/components/watermark/index.js
  src/components/watermark/watermark.js
  src/styles/style.scss
  src/ui-presets/live.js
  src/ui-presets/playback.js
  src/utils/component-config.js
Labels: Priority: High, Type: Feature

#193 fix(FEC-7964): touch while playing on mobiles always pause/resume the video
  src/components/shell/shell.js
Labels: Priority: High, Type: Bug

#194 fix(FEC-7988): [watermark] - when using a custom image it partially h…
  src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
  src/components/watermark/_watermark.scss
Labels: Priority: High

#195 fix(FEC-7992): on replay, hovering causes watermark to move up and down
  src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
Labels: Priority: High, Type: Bug

#197 fix(FEC-7990): captions do not move down when the bottom bar disappears
  src/styles/_captions.scss
Labels: Priority: High, Type: Bug

#196 fix: join menu open states to one generic state
  dist/playkit-ui.js
  dist/playkit-ui.js.map
  src/components/bottom-bar/bottom-bar.js
  src/components/language/language.js
  src/components/settings/settings.js
  src/components/shell/shell.js
  src/components/smart-container/smart-container.js
  src/reducers/language.js
  src/reducers/settings.js
  src/reducers/shell.js
  src/store.js
Labels: Priority: High, Type: Bug

#199 fix(FEC-7991): when changing captions language, the captions and playbar stay visible all the time
  src/components/seekbar/seekbar.js
  src/components/shell/shell.js
  src/components/volume/volume.js
Labels: Priority: High

#200 fix(FEC-8012): captions on ipad displayed in center
  src/components/fullscreen/_fullscreen.scss
  src/components/fullscreen/fullscreen.js
Labels: Priority: High, Type: Bug

#202 fix: move watermark behind everything
  src/components/watermark/_watermark.scss
Labels: Priority: High

#203 fix(FEC-8027): autoPlay fallback: the video doesn't unmuted by player…
  src/components/shell/shell.js
Labels: Priority: High, Type: Bug

#204 fix(FEC-8012): captions on ipad displayed in center
  src/components/fullscreen/_fullscreen.scss
  src/components/fullscreen/fullscreen.js
  src/styles/_shell.scss
Labels: Priority: High, Type: Bug

#206 fix(FEC-8024): black screen on replay - ie11
  src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
Labels: Priority: High, Type: Bug
