Repository kaltura/playkit-js-ui, pull requests merged in 2018-12, with the labels that each got.

#308 feat(FEC-8671): add CVAA menu labels/ids to enable external CSS to customize it
  docs/cvaa-override.md
  docs/ui-customization.md
  src/components/cvaa-overlay/_cvaa-overlay.scss
  src/components/cvaa-overlay/cvaa-overlay.js
Labels: Priority: Medium, Type: Feature

#311 fix(FEC-8747): no play button when auto play failed
  src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
Labels: Priority: High, Type: Bug

#312 fix(FEC-8750): playlist countdown is not fit to the player size
  src/components/playlist-countdown/_playlist-countdown.scss
Labels: Priority: High, Type: Bug

#305 fix(FEC-8710): watermark covers the playlist countdown
  src/components/vr-stereo-toggle/vr-stereo-toggle.js
  src/components/watermark/watermark.js
  src/ui-presets/live.js
  src/ui-presets/playback.js
  src/utils/component-config.js
Labels: Priority: High, Type: Bug

#306 feat(FEC-8682): end screen
  src/components/bottom-bar/_bottom-bar.scss
  src/components/cast-on-tv/cast-after-play.js
  src/components/cast-on-tv/cast-before-play.js
  src/components/cast-on-tv/index.js
  src/components/engine-connector/engine-connector.js
  src/components/index.js
  src/components/play-pause/play-pause.js
  src/components/playlist-button/_playlist-button.scss
  src/components/playlist-countdown/_playlist-countdown.scss
  src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
  src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
  src/components/shell/shell.js
  src/components/top-bar/_top-bar.scss
  src/components/unmute-indication/_unmute-indication.scss
  src/components/unmute-indication/unmute-indication.js
  src/components/watermark/_watermark.scss
  src/reducers/engine.js
  src/reducers/shell.js
  src/styles/_captions.scss
  src/styles/_control-button.scss
  src/styles/_shell.scss
  src/styles/style.css
Labels: Priority: High, Type: Feature

#313 fix: stereo button is shown for non-vr content
  src/components/vr-stereo-toggle/vr-stereo-toggle.js
Labels: Priority: High, Type: Bug

#314 fix: uncaught exception from playlist countdown component
  src/components/playlist-countdown/playlist-countdown.js
Labels: Priority: High, Type: Bug

#310 fix(FEC-8738): mobile - when there are 2 players in a page, the settings from the 2nd are presented on the first
  src/components/error-overlay/error-overlay.js
  src/components/language/language.js
  src/components/overlay-portal/overlay-portal.js
  src/components/settings/settings.js
  src/components/smart-container/smart-container.js
  src/styles/_shell.scss
  src/styles/style.css
Labels: Priority: High, Type: Bug

#316 fix(FEC-8771): cvaa - background opacity does not have specific class
  src/components/cvaa-overlay/cvaa-overlay.js
Labels: Type: Bug

#315 fix(FEC-8614): play/pause is stuck in chrome-mobile mode
  src/components/overlay-action/overlay-action.js
Labels: Priority: High, Type: Bug

#325 fix(FEC-8799): video not unmuted by tapping on player or seek by dragging
  src/components/shell/shell.js
Labels: Priority: High, Type: Bug

#321 fix(FEC-8781): simplify center ui elements
  src/components/playlist-next-screen/_playlist-next-screen.scss
Labels: Priority: High, Type: Bug
