Repository kaltura/playkit-js-ui, pull requests merged in 2018-09, with the labels that each got.

#269 feat(FEC-7681): add i18n support
  docs/configuration.md
  docs/translations.md
  flow-typed/types/ui-options.js
  src/components/ad-learn-more/ad-learn-more.js
  src/components/ad-notice/_ad-notice.scss
  src/components/ad-notice/ad-notice.js
  src/components/ad-notice/index.js
  src/components/ad-skip/ad-skip.js
  src/components/cvaa-overlay/cvaa-overlay.js
  src/components/error-overlay/error-overlay.js
  src/components/live-tag/live-tag.js
  src/components/overlay/overlay.js
  src/components/unmute-indication/unmute-indication.js
  src/fr.json
  src/styles/style.scss
  src/translations/en.json
  src/ui-manager.js
  src/ui-presets/ads.js
Labels: Type: Feature

#270 docs: fix syntax error
  docs/custom-ui-preset.md
Labels: Type: Docs

#272 fix: use 'player.ads.skipAd()' instead of 'player.skipAd()'
  src/components/ad-skip/ad-skip.js
Labels: Priority: High
