Repository kaltura/playkit-js-ui, pull requests merged in 2019-01, with the labels that each got.

#327 fix(FEC-8806): playlist - next item screen - the text is not centered
  src/components/playlist-next-screen/_playlist-next-screen.scss
Labels: Priority: High, Type: Bug

#331 fix(FEC-8827): cast button is not centered
  src/components/cast-on-tv/_cast-on-tv.scss
Labels: Priority: High, Type: Bug

#328 fix(FEC-8258): captions and audio 'for' attribute is set to 'quality'
  src/components/dropdown/dropdown.js
  src/components/smart-container/smart-container-item.js
Labels: Priority: Low

#330 fix(FEC-8827): cast button is redundant and unreachable on replay
  src/components/cast-on-tv/cast-before-play.js
Labels: Priority: High, Type: Bug

#317 fix(FEC-8572): change the way the player compute text tracks font size
  src/components/cvaa-overlay/cvaa-overlay.js
Labels: Priority: High, Type: Bug

#329 feat(FEC-8817): support horizontal volume bar
  src/components/volume/volume.js
Labels: Priority: Low, Type: Feature

#332 feat(FEC-8703): playlist loop
  src/components/playlist-countdown/playlist-countdown.js
  src/components/pre-playback-play-overlay/pre-playback-play-overlay.js
Labels: Priority: High, Type: Feature

#335 chor(FEC-8847): docs for horizontal volume bar
  docs/components/seekbar/README.md
  docs/css-classes-override.md
Labels: Priority: Low

#334 feat(FEC-8124): render player ads UI (also on mobile) unless configured else
  src/components/top-bar/_top-bar.scss
  src/ui-presets/ads.js
Labels: Priority: High

#337 fix(FEC-8846): current caption disappear after changing its style in advanced settings
  src/styles/_captions.scss
Labels: Priority: Medium

#338 fix: icons not shown on a white background
  src/components/icon/icon.scss
Labels: Priority: High, Type: Bug

#324 fix(FEC-8717): when player ui is small the captions language options dropdown is cut
  src/components/dropdown/dropdown.js
  src/components/language/language.js
  src/components/menu/menu.js
  src/components/settings/settings.js
  src/components/shell/shell.js
  src/components/smart-container/_smart-container.scss
  src/components/smart-container/smart-container.js
  src/reducers/shell.js
Labels: Priority: High, Type: Bug

#339 fix: icon style is duplicate
  src/styles/style.scss
Labels: Priority: High, Type: Bug

#336 fix(FEC-8852): closing pip window on Mac with Safari the video dose not return to the player
  src/components/engine-connector/engine-connector.js
Labels: Priority: High

#340 fix(FEC-8866): 'skip ad' button is covered by the control bar on mobile devices
  src/ui-presets/ads.js
Labels: Priority: High, Type: Bug

#342 fix(FEC-8768): seeking back on ended doesn't work when casting
  src/components/bottom-bar/bottom-bar.js
  src/components/cast-on-tv/cast-after-play.js
  src/components/cast-on-tv/index.js
  src/components/index.js
  src/components/top-bar/_top-bar.scss
  src/components/top-bar/top-bar.js
Labels: Priority: High, Type: Bug

#341 fix(FEC-8717): the dropdown is cut on large amount of options
  src/components/menu/menu.js
  src/styles/_dropdown.scss
Labels: Priority: Medium, Type: Bug
