Repository kaltura/playkit-js-ui, pull requests merged in 2019-03, with the labels that each got.

#362 fix(FEC-8948): play/pause icons (in middle player) are not changing according to player size
  src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
Labels: Priority: High

#363 fix(FEC-8960): need to tap on Play button more than one time in order to start playback on iOS
  src/components/pre-playback-play-overlay/_pre-playback-play-overlay.scss
Labels: Priority: High, Type: Bug

#364 fix(FEC-8961): the play button located not in the middle of the player
  src/styles/style.css
Labels: Priority: High, Type: Bug

#367 fix(FEC-8980): size CSS class is incorrect if player is rendered when detached from DOM
  src/components/shell/shell.js
Labels: Type: Bug

#368 fix(FEC-7642): firefox speed selector keyboard shortcut doesnt work
  src/ui-manager.js
  src/utils/key-map.js
Labels: Type: Bug
