Repository kaltura/playkit-js-ui, pull requests merged in 2019-02, with the labels that each got.

#343 fix: cast ui shows replay button when seeking after replay
  src/components/bottom-bar/_bottom-bar.scss
  src/components/bottom-bar/bottom-bar.js
  src/components/top-bar/_top-bar.scss
  src/components/top-bar/top-bar.js
Labels: Priority: High, Type: Bug

#344 fix(FEC-8885): smart menu doesn't open if no label is supplied
  src/components/smart-container/smart-container-item.js
Labels: Priority: High

#345 fix(FEC-8888): the playback paused when tap on "unmute" button on Android
  src/components/unmute-indication/unmute-indication.js
Labels: Priority: High

#349 fix(FEC-8905): default drop-downs options in IE and Edge are not visible
  src/components/smart-container/_smart-container.scss
Labels: Priority: Medium

#346 feat(FEC-8868): mobile ads preset
  src/components/bottom-bar/_bottom-bar.scss
  src/ui-presets/ads.js
Labels: Priority: Medium

#350 fix(FEC-8903): when loading a player with display: none, the player size class is set to small
  src/components/shell/shell.js
Labels: Priority: Medium

#354 fix(FEC-8926): Subtitles are hidden by the seek bar on none Safari browsers in iOS
  src/styles/_captions.scss
Labels: Type: Bug

#351 fix(FEC-8565): bottom bar is not clickable when the loading overlay is displayed
  src/components/loading/_loading.scss
Labels: Priority: Medium

#353 feat(FEC-8294): toggle unmute on volume icon click when volume was decreased to zero via dragging
  src/components/volume/volume.js
Labels: Priority: Medium

#348 feat(FEC-8454): handle small player views
  src/components/bottom-bar/_bottom-bar.scss
  src/components/dropdown/dropdown.js
  src/components/language/language.js
  src/components/menu/menu.js
  src/components/picture-in-picture/picture-in-picture.js
  src/components/playback-controls/_playback-controls.scss
  src/components/seekbar/_seekbar.scss
  src/components/settings/settings.js
  src/components/shell/shell.js
  src/components/smart-container/_smart-container.scss
  src/components/smart-container/smart-container.js
  src/components/time-display/_time-display.scss
  src/components/volume/_volume.scss
Labels: Priority: Medium
