Repository kaltura/playkit-js-ui, pull requests merged in 2019-04, with the labels that each got.

#369 feat(FEC-8662): share component
  flow-typed/types/components-config.js
  flow-typed/types/share-config.js
  src/components/copy-button/_copy-button.scss
  src/components/copy-button/copy-button.js
  src/components/copy-button/index.js
  src/components/error-overlay/_error-overlay.scss
  src/components/error-overlay/error-overlay.js
  src/components/icon/icon.js
  src/components/icon/icon.scss
  src/components/keyboard/keyboard.js
  src/components/share-overlay/_share-overlay.scss
  src/components/share-overlay/share-overlay.js
  src/components/share/default-config.js
  src/components/share/share.js
  src/components/share/share.scss
  src/reducers/config.js
  src/reducers/share.js
  src/styles/_inputs.scss
  src/styles/style.css
  src/styles/style.scss
  src/translations/en.json
  src/ui-presets/live.js
  src/ui-presets/playback.js
Labels: Type: Feature

#370 fix(FEC-8826): fullscreen implementation moved to core
  docs/configuration.md
  flow-typed/types/components-config.js
  flow-typed/types/fullscreen-config.js
  src/components/engine-connector/engine-connector.js
  src/components/fullscreen/_fullscreen.scss
  src/components/fullscreen/fullscreen.js
  src/components/shell/shell.js
  src/reducers/engine.js
  src/reducers/fullscreen.js
  src/reducers/index.js
  src/store.js
Labels: Type: Maintenance

#374 fix(FEC-9006): invalid share CSS portal selector
  src/components/share/share.js
Labels: Type: Bug

#375 fix(FEC-9010): share button shows on preplay screen
  src/ui-presets/live.js
  src/ui-presets/playback.js
Labels: Type: Bug

#376 fix(FEC-9004): share copy link doesn't work on iOS
  src/components/share-overlay/share-overlay.js
Labels: Type: Bug

#378 fix(FEC-9005): no tooltip displayed on copy link icon
  src/components/copy-button/copy-button.js
  src/components/share-overlay/share-overlay.js
  src/translations/en.json
Labels: Type: Bug

#379 fix(FEC-9003): can't close share overlay on IE11
  src/components/share/share.js
  src/components/smart-container/smart-container.js
Labels: Type: Bug

#381 fix(FEC-9011): share button dose not work on end screen
  src/components/share/share.scss
Labels: Type: Bug

#380 fix(FEC-9015): share to email subject and body
  src/components/share-overlay/share-overlay.js
Labels: Type: Bug

#382 fix(FEC-8826): element sent from UI for fullscreen
  src/components/fullscreen/fullscreen.js
Labels: Type: Bug

#373 fix(FEC-8969): playlist - next screen poster displayed blurred with bad resolution
  src/components/playlist-countdown/_playlist-countdown.scss
  src/components/playlist-next-screen/_playlist-next-screen.scss
  src/components/playlist-next-screen/playlist-next-screen.js
Labels: Priority: High, Type: Bug

#372 fix(FEC-8924): [V3][iOS] when touch and dragging from player area the page is not scrolling
  src/components/overlay-action/overlay-action.js
Labels: Type: Bug

#384 fix(FEC-8937): UI icons rendered oddly in iOS
  src/components/icon/icon.scss
  src/components/playback-controls/_playback-controls.scss
Labels: Type: Bug
